name: ETL CSV to Snowflake Validation

on:
  workflow_dispatch:

jobs:
  etl_test_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL Pytest
        env:
          SF_USER: ${{ secrets.SNOWFLAKE_USER }}
          SF_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SF_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SF_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SF_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          pytest tests/test_migration_etl_validation.py -v

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ETL_Logs
          path: logs/

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ETL_Reports
          path: reports/
