name: ETL CSV to Snowflake Validation

on:
  schedule:
    - cron: '0 2 * * *'   # runs daily at 7:30 AM IST
  workflow_dispatch:

jobs:
  etl_test_job:
    runs-on: ubuntu-latest

    env:
      SF_USER: ${{ secrets.SNOWFLAKE_USER }}
      SF_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SF_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run ETL Pytest Validations
      run: |
        pytest tests/test_migration_etl_validation.py -v
